### ISSUE TITLE
make friend bro

### ISSUE THREAD

**Issue by BigBrotherHui** [Haitao-Lee/RSA-Preoperative-Planner#1]
may i have your wechat bro?

**Comment by BigBrotherHui** [comment]
i want some impant files,could you please give me some?

**Comment by Haitao-Lee** [comment]
No problem, my wechat ID is 'HunterLi_ID'.


| |
Hunter Li
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/4/2024 11:49 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [Haitao-Lee/RSA-Preoperative-Planner] make friend bro (Issue #1) |

i want some impant files,could you please give me some?
